config/routes.rb
Rails.application.routes.draw do
  root "invoices#index"
  resources :line_items
  resources :invoices
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :invoices
  validates_uniqueness_of :email
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :client
  has_many :line_items, dependent: :destroy
  accepts_nested_attributes_for :line_items, :allow_destroy => true, reject_if: :all_blank
  after_create :calculate_amount

  enum :status, [:due, :paid, :over_due, :void]


  def calculate_amount
    value = 0
    self.line_items.each do |item|
      value += (item.amount.to_f * item.quntity.to_f)
    end
    self.update_columns(amount: value)
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :invoice
  after_save_commit :update_invoice
  after_update :update_invoice
  after_destroy :update_invoice

  def update_invoice
    self.invoice.calculate_amount
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :address, :email, :phone, :dob)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1 or /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @invoice.line_items.build
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:amount, :due_date, :status, :paid_on, :client_id, line_items_attributes: [:id, :description, :amount, :quntity, :_destroy])
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    @line_item = LineItem.new(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully created." }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:description, :amount, :quntity, :invoice_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def badge_color(status)
    case status
      when "due"
        return "badge text-bg-info text-uppercase"
      when "paid"
        return "badge text-bg-success text-uppercase"
      when "over_due"
        return "badge text-bg-danger text-uppercase"
      else
        return "badge text-bg-secondary text-uppercase"
      end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/clients/_client.html.erb
<td><%= link_to "#{client.name}", client_path(client) %></td>
<td><%= client.address %></td>
<td><%= client.email %></td>
<td><%= client.phone %></td>
<td><%= client.dob %></td>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :dob, style: "display: block" %>
    <%= form.text_field :dob %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clients</h1>
<%= link_to "New client", new_client_path %>

<table id="table" class="table table-striped">
  <thead>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>DOB</th>
    <th>Action</th>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <%= render client %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to '< Back', clients_path %>

<div class="card" style="width: 25rem;">
  <%= image_tag Faker::LoremFlickr.image, class: "card-img-top", alt:"..." %>
  <div class="card-body">
    <h5 class="card-title"><%= @client.name %></h5>
    <p class="card-text"><%= @client.address %></p>
    <p><%= link_to "Edit this client", edit_client_path(@client) %> | <%= link_to "Back to clients", clients_path %> </p>
    <p><%= button_to "Destroy this client", @client, method: :delete, class: "btn btn-link" %></p>
  </div>
</div>
<div>
  <table class="table table-striped">
    <thead>
      <th>Invoice ID</th>
      <th>Amount</th>
      <th>Status</th>
      <th>Due Date</th>
      <th>Action</th>
    </thead>
    <tbody>
      <% if @client.invoices.present? %>
        <% @client.invoices.each do |invoice| %>
          <tr>
            <td><%= invoice.id %></td>
            <td><%= invoice.amount %></td>
            <td><%= invoice.status %></td>
            <td><%= invoice.due_date.strftime("%d %b %Y") %></td>
            <td><%= link_to 'Show Invoice details', invoice_path(invoice)%></td>
          </tr>
        <% end %>
      <% else %>
          <tr><td colspan="4">No Data</td></tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/invoices/_form.html.erb
<%= nested_form_for @invoice do |form| %>
  <% if invoice.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.select :client_id, Client.all.map {|c| [c.name, c.id]} %>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.datetime_field :due_date %>
  </div>

  <%= form.fields_for :line_items do |item| %>
    <div>
      <%= item.label :Description %>
      <%= item.text_field :description %>
    </div>

    <div>
      <%= item.label :amount %>
      <%= item.text_field :amount %>
    </div>
    
    <div>
      <%= item.label :quntity %>
      <%= item.text_field :quntity %>
    </div>
    
    <%#= item.link_to_remove "Remove this line item" %>
  <% end %>
  <p><%#= form.link_to_add "Add new line item", :line_items %></p>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/_invoice.html.erb
<div class="card" style="width: 38rem;">
  <div class="card-header">
    <div id="status" class="<%= badge_color(invoice.status) %>"><%= invoice.status %></div>
    <h5 class="card-title"><%= invoice.client.name %> INV - <%= invoice.id %></h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Due on - <%= invoice.due_date.strftime("%d %b, %Y") %></li>
    <li class="list-group-item"><%= link_to "Show this invoice", invoice %></li>
  </ul>
</div>

<style type="text/css">
  #status{
    float: right;
  }
</style>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render "form", invoice: @invoice %>

<br>

<div>
  <%= link_to "Show this invoice", @invoice %> |
  <%= link_to "Back to invoices", invoices_path %>
</div>

app/views/invoices/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Invoices</h1>
<%= link_to "New invoice", new_invoice_path %>

<div id="invoices">
  <% @invoices.each do |invoice| %>
    <%= render invoice %>
  <% end %>
</div>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render "form", invoice: @invoice %>

<br>

<div>
  <%= link_to "Back to invoices", invoices_path %>
</div>

app/views/invoices/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card" style="width: 38rem;">
  <div class="card-header">
    <div class="status <%= badge_color(@invoice.status) %>"><%= @invoice.status %></div>
    <h2 class="status"><%= @invoice.amount %></h2>
    <h6 class="card-title">INV - <%= @invoice.id %></h6>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Due on - <%= @invoice.due_date.strftime("%d %b, %Y") %></li>
    <li class="list-group-item"><a href="#" class="card-link">Send Invoice</a></li>
    <li class="list-group-item"><a href="#" class="card-link">Payment</a></li>
  </ul>
</div>


<div>
  <table class="table table-striped">
    <thead>
      <th>LineItem ID</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Quntity</th>
      </thead>
    <tbody>
      <% if @invoice.line_items.present? %>
        <% @invoice.line_items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= item.description %></td>
            <td><%= item.amount %></td>
            <td><%= item.quntity %></td>
          </tr>
        <% end %>
      <% else %>
          <tr><td colspan="4">No Data</td></tr>
      <% end %>

    </tbody>
  </table>
</div>

<style type="text/css">
  .status{
    float: right;
  }
</style>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Home', root_path, class: "navbar-brand" %>
    <!-- for mobile view -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- for mobile view end -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Invoices', invoices_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Clients', clients_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profiles
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><%#= button_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineBilling</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> -->
    <!-- <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script> -->
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application" %>
  </head>

  <%= render 'layouts/header' %>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :quntity, style: "display: block" %>
    <%= form.text_field :quntity %>
  </div>

  <div>
    <%= form.label :invoice_id, style: "display: block" %>
    <%= form.text_field :invoice_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<div id="<%= dom_id line_item %>">
  <p>
    <strong>Description:</strong>
    <%= line_item.description %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= line_item.amount %>
  </p>

  <p>
    <strong>Quntity:</strong>
    <%= line_item.quntity %>
  </p>

  <p>
    <strong>Invoice:</strong>
    <%= line_item.invoice_id %>
  </p>

</div>

app/views/line_items/edit.html.erb
<h1>Editing line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Show this line item", @line_item %> |
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Line items</h1>

<div id="line_items">
  <% @line_items.each do |line_item| %>
    <%= render line_item %>
    <p>
      <%= link_to "Show this line item", line_item %>
    </p>
  <% end %>
</div>

<%= link_to "New line item", new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @line_item %>

<div>
  <%= link_to "Edit this line item", edit_line_item_path(@line_item) %> |
  <%= link_to "Back to line items", line_items_path %>

  <%= button_to "Destroy this line item", @line_item, method: :delete %>
</div>